Gabriela/django app
DadosAbertosDeFeira/pedidos pull request #1
Opened 2021-08-25 10:41 UTC by turquetti

Oi Ana!

Estou mandando a PR com:

- Ambiente virtual Poetry configurado;
- Aplicação do Django instalada e iniciada. 

Algumas dúvidas vieram durante esse processo, desde boas práticas na organização e nomeação do projeto em si até como incluir o banco de dados do PostgreSQL, mas imagino que teremos tempo para esclarecer isso mais tarde. :-)

2021-08-25 10:42 UTC, turquetti commented
Ah, eu acabei precisando reverter um commit, e refiz alguns pontos. Leve em consideração somente o commit mais recente!

2021-08-25 16:30 UTC, anapaulagomes requested changes
Está ficando ótimo! Precisamos adicionar também instruções de como as pessoas podem configurar o projeto.

2021-08-25 16:30 UTC, anapaulagomes commented on pedidos-env/pedidos_django/settings.py
> +SECRET_KEY = 'django-insecure-6=gg&cj8h81*@uctsisajvd@e)7nwfozx%^8+qub39=aiq^)t9'
```suggestion
import os
[...]
SECRET_KEY = os.getenv("SECRET_KEY")
```

2021-08-25 16:47 UTC, anapaulagomes commented
Podemos remover o `pedidos-env/README.rst` pq já temos o README.md.

2021-09-02 13:57 UTC, turquetti commented
Ana, 

alterações do Código Inicial #1 feitas. 

Fiz outro commit nessa mesma branch. :D

2021-09-02 16:33 UTC, anapaulagomes approved these changes
Boa! 🤓

2021-09-02 16:33 UTC, merged