adiciona alterações no admin
DadosAbertosDeFeira/pedidos pull request #21
Opened 2021-09-22 14:46 UTC by turquetti

Ana, 

- Já inclui a parte condicional pro cálculo da diferença de dias dos pedidos, mas apesar do bloco de código rodar certinho no shell, quando olho lá no admin, a contagem de dias não se altera, não sei se é algum problema aqui;

- E tentei fazer o processo das migrations como você me ensinou, mas deu um errinho na migration 0002: `sqlite3.IntegrityError: NOT NULL constraint failed: new__pedidos_pedido.esfera`

2021-09-22 16:07 UTC, anapaulagomes commented on pedidos/admin.py
> +    def dias_sem_resposta(self, pedido):
Você fez o cálculo em um e não no outro (lembra da sugestão sobre usar um Mixin pra evitar duplicação? é pra evitar esses problemas :)).

2021-09-22 16:14 UTC, anapaulagomes commented on pedidos/migrations/0003_rename_esfera_orgao_orgao_esfera.py
> +    ]
O erro que você mencionou provavelmente acontece pq com as mudanças que esse campo sofreu ao longo das migrations não seria possível refazer de trás pra frente. Podemos deixar assim por enquanto e antes de ir pra produção fazemos um super merge. hehe

2021-09-22 18:24 UTC, turquetti commented on pedidos/migrations/0003_rename_esfera_orgao_orgao_esfera.py
> +    ]
tá bom!!!!!

2021-09-22 18:25 UTC, turquetti commented on pedidos/admin.py
> +    def dias_sem_resposta(self, pedido):
Tá bom! Eu vou procurar sobre o Mixin e tento implementar! :D

2021-09-27 11:42 UTC, anapaulagomes commented on pedidos/admin.py
> +from pedidos.models import Denuncia, Orgao, Pedido
👮🏽‍♀️

2021-09-27 11:42 UTC, anapaulagomes requested changes
Só precisamos nos livrar da denúncia por aqui e estamos prontas!

2021-09-27 11:42 UTC, anapaulagomes commented on pedidos/admin.py
> +class DenunciaModelAdmin(admin.ModelAdmin):
👀

2021-09-27 11:49 UTC, anapaulagomes commented on pedidos/admin.py
> +class DenunciaModelAdmin(admin.ModelAdmin):
Acho que basta atualizar a branch com a `main` e testar as migrations localmente.

2021-09-28 07:02 UTC, anapaulagomes approved these changes

2021-09-28 07:02 UTC, merged